apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ppc91ty5r-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ppc91ty5r-java-quarkus-gitops